{% set version = "0.6.0.dev1" %}

package:
  name: vispy
  version: {{ version }}

source:
  git_url: https://github.com/vispy/vispy.git
  git_rev: 47f3cd0cf179286774b8ec5d1fbe063a28b8e56b
  patches:
    - ctypes_fontconfig.diff

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy 1.11.*
    - fontconfig  # [unix]
    - gcc  # [linux]
    - cython

  run:
    - python
    - numpy >=1.11
    - fontconfig  # [unix]
    - scikit-image

test:
  imports:
    - vispy

about:
  home: http://vispy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'VisPy is a high-performance interactive 2D/3D data visualization library.'
