# Configuration of display features
display:
  # Choose from three options how to represent and display images (i.e. raster
  # data, data with an AreaDefinition):
  # - simple_geolocated: reprojected image (without dynamic tiling and
  #   resampling), best for powerful graphics hardware (default)
  # - tiled_geolocated: reprojected image with dynamic tiling and resampling
  # - pixel_matrix: original image, i.e. neither reprojected nor resampled
  image_mode: simple_geolocated
