data_reading:
  # define readers to activate in open file wizard
  readers:
    - abi_l1b
    - fci_l1_cat_lmk_loc
    - fci_l1_geoobs_lmk_loc
    - fci_l1_geoobs_lmk_nav_err
    - fci_l1c_nc
    - fci_l1c_iqt_fdhsi
    - fci_l2_nc
    - li_l1b_nc
    - li_l1b_bck_nc_sift
    - li_l2_nc
    - li_l2_a_nc_sift
    - seviri_l1b_hrit
    - seviri_l1b_native
    - seviri_l1b_nc
    - seviri_l2_binary
    - seviri_l2_bufr
    - seviri_l2_grib
    - avhrr_l1b_eps
    - vii_l1b_nc
    - gld360_ualf2
    - modis_l1b


