data_reading:
  readers:
    - fci_l1_cat_lmk_loc
    - fci_l1_geoobs_lmk_loc
    - fci_l1_geoobs_lmk_nav_err
    - fci_l1c_fdhsi
    - fci_l1c_iqt_fdhsi
    - li_l1b_bck_nc
    - seviri_l1b_hrit
    - seviri_l1b_nc
    - seviri_l1b_native
    - vii_l1b_nc
    - vii_l2_nc
    - avhrr_l1b_eps
    - gld360_ualf2
#  exclude_datasets:
#    calibration:
#      - counts
