package:
  name: cspov
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../../
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - python
    - setuptools
    - numpy
    - matplotlib
    - scipy
    - numba
    - pyproj >=1.9.4
    - vispy ==0.5.0dev
    - pyopengl
    - netcdf4
    - h5py
    - pillow
    - pyshp ==1.2.1
    - shapely ==1.5.11
    - rasterio
    - gdal
    - pyqt
    - cython >=0.17 # [win]

  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - numba
    - pyproj >=1.9.4
    - vispy ==0.5.0dev
    - pyopengl
    - netcdf4
    - h5py
    - pillow
    - pyshp ==1.2.1
    - shapely ==1.5.11
    - rasterio
    - gdal
    - pyqt

test:
  commands:
    - "python -m cspov -h"

about:
  #home: The package home page
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'Visualization Tool for Geostationary satellite imagery data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
