{% set data = load_setup_py_data() %}

package:
  name: cspov
  version: {{ data.get('version') }}

source:
  path: ../../py/
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - python
    - setuptools
    - numpy
    - matplotlib
    - scipy
    - numba
    - pyproj >=1.9.4
    - vispy ==0.5.0dev
    - pyopengl
    - netcdf4
    - h5py
    - pillow
    - pyshp ==1.2.1
    - shapely ==1.5.11
    - rasterio
    - gdal >=1.11.4 # [unix]
    - gdal ==1.11.2 # [win]
    - pyqt ==4.10.4
    - cython >=0.17 # [win]

  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - numba
    - pyproj >=1.9.4
    - vispy ==0.5.0dev
    - pyopengl
    - netcdf4
    - h5py
    - pillow
    - pyshp ==1.2.1
    - shapely ==1.5.11
    - rasterio
    - gdal >=1.11.4 # [unix]
    - gdal ==1.11.2 # [win]
    - pyqt ==4.10.4

test:
  commands:
    - "python -m cspov -h"

about:
  #home: The package home page
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'Visualization Tool for Geostationary satellite imagery data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
