default_colormaps:
  toa_bidirectional_reflectance:
    colormap_name: Square Root (Vis Default)
#    climits: (0, 255)
  toa_brightness_temperature:
    colormap_name: Rainbow (IR Default)
  brightness_temperature:
    colormap_name: Rainbow (IR Default)
  height_at_cloud_top:
    colormap_name: Cloud Top Height
  air_temperature:
    colormap_name: Rainbow (IR Default)
  relative_humidity:
    colormap_name: Rainbow (IR Default)
  # thermodynamic_phase_of_cloud_water_particles_at_cloud_top: Cloud Phase
  vis_08_east_sector:
    colormap_name: Square Root (Vis Default)
  vis_08_north_sector:
    colormap_name: Square Root (Vis Default)
  vis_08_south_sector:
    colormap_name: Square Root (Vis Default)
  vis_08_west_sector:
    colormap_name: Square Root (Vis Default)
