point_styles:
  red_x:
    # Allowed values: disc, arrow, ring, clobber, square, diamond, vbar, hbar,
    # cross, tailed_arrow, x, triangle_up, triangle_down, star
    symbol: 'x'
    size: '9px'
    fill: '#FF0000'
    stroke: #000000
    stroke-width: '2px'
    
  red_empty_square:
    symbol: 'square'
    size: '2%'
    stroke: '#FF0000'
    stroke-width: '1px'
