default_colormaps:
  toa_bidirectional_reflectance:
    colormap: Square Root (Vis Default)
#    range: [-1.2, 120]
  toa_brightness_temperature:
    colormap: Rainbow (IR Default)
  brightness_temperature:
    colormap: Rainbow (IR Default)
  height_at_cloud_top:
    colormap: Cloud Top Height
  air_temperature:
    colormap: Rainbow (IR Default)
  relative_humidity:
    colormap: Rainbow (IR Default)
  # thermodynamic_phase_of_cloud_water_particles_at_cloud_top: Cloud Phase
  vis_08_east_sector:
    colormap: Square Root (Vis Default)
  vis_08_north_sector:
    colormap: Square Root (Vis Default)
  vis_08_south_sector:
    colormap: Square Root (Vis Default)
  vis_08_west_sector:
    colormap: Square Root (Vis Default)
