# Overwrite the default import path for the Sapty package
# This can be used during development to load a different version of Satpy without the need to package it first
#satpy_import_path: "path/to/satpy"

# Make special fci_l1_geoobs reader (see
# https://gitlab.eumetsat.int/Meraner/fci_l1_geoobs_satpy_reader) available
# NOTE: this option may be a temporary solution
#satpy_fci_l1_geoobs_import_path: "path/to/fci_l1_geoobs_satpy_reader"
