data_reading:
  readers:
    - abi_l1b
    - fci_l1_cat_lmk_loc
    - fci_l1_geoobs_lmk_loc
    - fci_l1_geoobs_lmk_nav_err
    - fci_l1c_fdhsi
    - seviri_l1b_hrit
    - avhrr_l1b_eps
  exclude_datasets:
    calibration:
      - radiance
      - counts
